### ISSUE TITLE
Too much printing to screen when catch[no_area,] is large

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#102]
https://github.com/pfmc-assessments/nwfscSurvey/blob/98a2960c213adbe2a11d13aa52d31595cddddd8c/R/pull_catch.R#L227-L228

led to 48712 rows that were attempted to print to the screen when I ran
```
nwfscSurvey::pull_catch(survey = "NWFSC.Slope")
```
I think we should implement a check to see how large `no_area` is and truncate the printing if it is over a certain size and warn the user that just a few rows are shown.

**Comment by chantelwetzel-noaa** [comment]
This have been revised in pull request #156 reducing what is printed to the screen.
