### ISSUE TITLE
Units off for kg2 -> hectare conversion

### ISSUE THREAD

**Issue by ericward-noaa** [pfmc-assessments/nwfscSurvey#104]
Nick pointed this out -- there's 100 km2 in 1 hectare, so this 0.01 should be replaced by 100

https://github.com/pfmc-assessments/nwfscSurvey/blob/83ea0a48e52fb5f55e60459efd2876615ffe6a15/R/PullCatch.fn.R#L305

**Comment by Curt-Whitmire-NOAA** [comment]
@ericward-noaa , There's actually [100 hectares in 1 km2](https://www.google.com/search?q=convert+1+square+kilometer+to+hectares&rlz=1C5GCEM_enUS996US1003&ei=OZjNY5i7DLqN0PEPsdiJoA0&oq=convert+1+square+ki&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAxgAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgUIABCGAzIFCAAQhgMyBQgAEIYDOgoIABBHENYEELADOgUIABCRAjoFCAAQgAQ6BQghEKABOgUIIRCrAjoICCEQFhAeEB1KBAhBGABKBAhGGABQkAVY1RBg5R1oAXABeACAAZEBiAHwBpIBAzguMpgBAKABAcgBCMABAQ&sclient=gws-wiz-serp), but Nick is right that this formula should either multiply by 100 or divide by 0.01.

**Comment by chantelwetzel-noaa** [comment]
@ericward-noaa @Curt-Whitmire-NOAA Thank you  both for catching this. I accidently introduced this error in August 2022 when I was checking units throughout the package. I inadvertently converted from hectares to km2 without considering that the units were in the denominator.  267f718f8109cc85182a7c320383192f9d892128 fixes this issue.

**Comment by ericward-noaa** [comment]
@chantelwetzel-noaa @Curt-Whitmire-NOAA I think this is still not quite right. I just installed the latest version, and confirmed the `cpue_kg_per_ha_der` matches FRAM Data Explorer. But I think the conversion to km2 is backwards -- using an example from yelloweye CPUE in 2021, 

```
d = pull_catch(common_name = "yelloweye rockfish", survey="NWFSC.Combo", years = 2021)
range(d$cpue_kg_per_ha_der) # returns 0 - 23.11421
range(d$cpue_kg_km2) # returns 0 - 0.2311421
```

And when I look at doing it manually,
```
range(z$cpue_kg_per_ha_der * 100) # returns 0 - 2311.421
```

Lots of online examples to double check this, e.g. https://www.kylesconverter.com/area-density/kilograms-per-hectare-to-kilograms-per-square-kilometer

**Comment by chantelwetzel-noaa** [comment]
@ericward-noaa @Curt-Whitmire-NOAA The commit with the revision is included in a pull request currently under review (get_strata branch). Is the correction in this branch correct (267f718f8109cc85182a7c320383192f9d892128)?  The review has been slightly delayed due to hake.  If it is not completed today, I can cherry pick this commit into the main branch.

**Comment by ericward-noaa** [comment]
Ah - sorry, didn't realize it was still under review. Closing this because that formula is correct. Thanks!
