### ISSUE TITLE
Apparent ggplot Error in plot_comps.R

### ISSUE THREAD

**Issue by Ovec8hkin** [pfmc-assessments/nwfscSurvey#106]
The currently available version of 'plot_comps.R' yields the following error message when run on data generated from `SurveyLF.fn()`:

```
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :no font could be found for family "Year"
```

This can be traced back to the ggplot plot construction call shown below, in which the first parameter passed to `theme(axis.text.x=element_text(...)` is the axis name. 

```r
ggplot2::ggplot(df, aes(x = year, y = variable)) +
        geom_point(aes(size = value, fill = sex, colour = sex), # add alpha = n inside the aes to shade by annual sample size
          alpha = 0.75, shape = 21) +
        scale_fill_manual(values = c('FEMALE' = 'red', 'MALE' = 'blue', 'UNSEXED' = "darkseagreen")) +
        scale_color_manual(values = c('FEMALE' = 'darkred', 'MALE' = 'darkblue', 'UNSEXED' = "darkgreen")) +
        scale_size_continuous(limits = c(0.1, 50), range = c(1, max_range), breaks = bub_range) + 
        facet_grid(sex~.) + 
        scale_y_continuous(breaks = y_axis) +
        labs(x = "Year", y = ylabel, size = "Relative\nAbundance (%)", fill = "") +
        theme(
            legend.key = element_blank(), 
            axis.title.x = element_text (size = 12),
            axis.title.y = element_text (size = 1),
            axis.text.x = element_text("Year", colour = "black", size = 12, angle = 90, vjust = 0.3, hjust = 1),
            axis.text.y = element_text(ylabel, colour = "black", size = 12),
            legend.text = element_text(size = 10, colour ="black"),
            legend.title = element_text(size = 12),
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black", fill = NA, size = 1),
            legend.position = "right"
          ) +
        guides(size = "legend", color = "none", fill = "none")  
```

`element_text` objects expect the first parameter to be the font family to be used for rendering the axis label, rather than the axis name.

I believe simply removing the axis names from the `element_text` objects for `axis.text.x` and `axis.text.y` is sufficient for solving the problem.

**Comment by Ovec8hkin** [comment]
Happy to submit a fix, just need to know what the routine for submitting contributions is.

**Comment by chantelwetzel-noaa** [comment]
Thank you for reporting this error in detail which made it easy to fix. The correction has been pushed to the main branch.

**Comment by iantaylor-NOAA** [comment]
@Ovec8hkin, regarding "need to know what the routine for submitting contributions is", I'm not sure if the protocol has been spelled out for any of repositories within this pfmc-assessments organization. The lead maintainer of each individual package (in this case @chantelwetzel-noaa) may have a preferred approach, but I'm guessing that a pull request from a fork of the repo would always be welcome. And for a simple change like this a simple issue like you've posted is probably easier. It's good to get bugs fixed regardless of the method, so thank you for that.

**Comment by Ovec8hkin** [comment]
@iantaylor-NOAA @chantelwetzel-noaa 
I assumed that was the case, but wasn't sure if the full "fork, fix, pull request" routine was the standard case. I've been on some smaller repos that used alternative means for contributions. Also wasn't sure if there was a problem with contributing to official NOAA packages without being a NOAA employee (or having a formal NOAA GitHub profile).

In the future I will fork and submit a PR for small bugs like this.

**Comment by iantaylor-NOAA** [comment]
@Ovec8hkin, we have struggled to understand the rules around software created by U.S. federal government employees (and where is the line between NOAA software and software that NOAA folks just contribute to). For the pfmc-assessments organization, only NOAA folks can have push access, but I think contributions via pull requests from outside contributors are fine.
