### ISSUE TITLE
add option to pull data from unsatisfactory tows

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/nwfscSurvey#115]
There's been a discussion about the use of data from unsatisfactory tows during the during the ongoing Workshop on Refining the WCGBTS Sampling Frame. @Curt-Whitmire-NOAA pointed out that our current setup excludes all data from unsatisfactory tows, but Owen Hamel pointed out that there may be cases, such as when you're calculating the CAAL data for a relatively rare species like Yelloweye Rockfish, that it would be useful to include all available age/length pairs.

If length comps are being expanded based on the sample size relative to the total weight of the catch, so if we don't have confidence in the total weight of the unsatisfactory tow, then we may not trust the length comp. However, if the lengths are unexpanded, which is probably more common for rare species, then we may want to consider including tows that are unsatisfactory due to insufficient tow duration.

The people from the survey team at the meeting noted that sometimes only total weights are taken from the unsatisfactory tows but in other cases some rarer species (Yelloweye and Canary were mentioned), get at least sexed lengths. It's not clear how often otoliths have been taken from unsatisfactory tows or whether these samples would get prioritized for ageing.

The satisfactory filter is applied in places like
https://github.com/pfmc-assessments/nwfscSurvey/blob/main/R/PullBio.fn.R#L130
But if unsatisfactory tows were pulled, we would probably want to apply additional filtering on the reasons for being unsatisfactory.

I'm applying a "priority_low" label and assigning to a new "2025assessment" milestone to make it clear we don't need to worry about this right now.

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA Thanks for raising this issue. I for one was not aware of it. It would seem that the first order of business would be to determine for what species this issue matters. Presumably, we could narrow down our scope quite a bit by just providing the number/percentage of tows by species that are unsatisfactory, and then providing the number of lengths/ages by species that are available among the unsatisfactory tows.

**Comment by iantaylor-NOAA** [comment]
@brianlangseth-NOAA, good question. 
I tried commenting out the satisfactory tow filter noted the initial comment on this issue and got a total of 13,591 canary samples from the WCGBTS vs 13,307 with only good tows included. 75 out of the 284 extra samples had ages. I don't think that's enough to have an impact on anything you're doing in 2023.

However, raising awareness of the existence of such samples, getting access to the reasons why the tows were deemed unsatisfactory (too short, not on bottom, outside of cell, etc.), and compiling a table of the sample sizes across species of interest would be useful next steps.

**Comment by Curt-Whitmire-NOAA** [comment]
@iantaylor-NOAA , not sure how I missed this one, so sorry for the very late reply. The _[operation_haul_fact](https://www.webapps.nwfsc.noaa.gov/data/metadata/trawl.operation_haul_fact)_ table offers a field called **reason_unacceptable** that lists the reason(s) why I tow was determined to have 'unsatisfactory' performance.

**Comment by chantelwetzel-noaa** [comment]
This functionality has been added to each of the pull_* functions in pull request #156
