### ISSUE TITLE
mismatch between bio and catch data in WCGBTS data

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/nwfscSurvey#119]
@Curt-Whitmire-NOAA, here's one for you. 
This is low priority because we can rely on previous extractions, but good to figure out anyway.

@gertsevv and I are getting `Error in Area_Swept[find] <- area : replacement has length zero` that we didn't get a few months ago when extracting WCGBTS petrale data and creating length comps. It appears to be due to a haul no longer present in the catch extraction which is still present in the bio extraction.
```
> catch = PullCatch.fn(Name = "petrale sole", 
                     SurveyName = "NWFSC.Combo")
                     
> bio   = PullBio.fn(Name = "petrale sole", 
                   SurveyName = "NWFSC.Combo")

> table(bio$Trawl_id %in% catch$Trawl_id)
FALSE  TRUE 
   18 75747 
```
All 18 samples are from Trawl_id = 202103010023 which is the only haul that is not in the extraction but WAS in the extraction when I ran similar code in March:
```
> catch_old %>% dplyr::filter(!Trawl_id %in% catch$Trawl_id)
      Trawl_id  Common_name     Project Year Pass    Vessel Tow        Date Depth_m Longitude_dd Latitude_dd Area_Swept_ha
1 202103010023 petrale sole NWFSC.Combo 2021    1 Ms. Julie  23 2021-May-25   113.2    -125.0925    48.41056      1.440176
  Subsample_count Subsample_wt_kg CPUE_kg_per_ha total_catch_numbers total_catch_wt_kg cpue_kg_km2
1              18            9.45       67.14459                 185              96.7    6714.459
```
This haul is close to the U.S./Canada border, so perhaps it's been reclassified as outside of the survey extent? If that's the case, we should flag the bio data as well so it doesn't get included in the extraction, right?

**Comment by Curt-Whitmire-NOAA** [comment]
@iantaylor-NOAA @gertsevv thanks for flagging this problem. Jim Fellows and I are aware of it, and have identified the fix, but are hesitant to implement it in the middle of an assessment year as we aren't clear what the downstream effects may be.

@chantelwetzel-noaa  and @okenk reported a similar issue on 11 March, and it is the same tow (Trawl_id = 202103010023) in question.

We can either implement the fix now or wait until all the assessment data pulls are completed for the year. Any suggestions on if/when we should proceed?

**Comment by okenk** [comment]
From the perspective of canary, it shouldn't matter, as I don't anticipate re-pulling any survey data again this cycle. It doesn't look like our code excludes that tow, so we must have reverted back to an older pull.

**Comment by Curt-Whitmire-NOAA** [comment]
Thanks @okenk. To be clear, the issue seems to be related to a improper relationship in the backend database of the Data Warehouse. Tows where the target station differed from the actual station, and the actual station has been flagged to be invalid seem to be the culprit here. The proposed fix is to correct the relationship so both data pulls are filtering out any tow where the actual station has been flagged as invalid for whatever reason.

**Comment by kellijohnson-NOAA** [comment]
@Curt-Whitmire-NOAA from my perspective, I think it is always good to update the information regardless of where we are in an assessment cycle. But, I might be biased because I have yet to pull data for sablefish for the update and will be doing so soon.

**Comment by Curt-Whitmire-NOAA** [comment]
Thanks @kellijohnson-NOAA for those thoughts. If I don't hear any objections by mid-week, Jim and I will work to implement the changes to the DEV environment, do some testing, and then if all goes well push to PROD soon thereafter.

**Comment by iantaylor-NOAA** [comment]
@Curt-Whitmire-NOAA thanks for reporting what's going on behind the scenes and good to hear you have a fix on the way. I'm with @kellijohnson-NOAA in preferring that issues get sorted out as soon as it's convenient to do so. 

My only additional concern with changes in the middle of a busy assessment season is just keeping folks up to date that changes are being made. That way if things don't match perfectly before and after the change we know there's a reason for it. Some ways to communicate changes include:
1. sending an email to anyone on the NWFSC assessment team who could report to the rest of the team
2. posting an issue on this repository to notify all folks watching the repository
3. any other ideas you have to communicate this stuff?

**Comment by Curt-Whitmire-NOAA** [comment]
@iantaylor-NOAA thanks for your suggestions on providing enhanced communication about changes to underlying data, especially during an assessment season. I think we can easily accommodate #1 and #2 when we push station-related changes to the warehouse.

As far as updates to the data, we identified that the likely culprit is not with the relationship in the backend database, but most likely with the underlying data. We learned that changes to station assignments in the _operation_haul_fact_ table don't necessarily propagate to changes in the station assignments to either the _catch_fact_ or _individual_fact_ tables. We are developing a workflow for preventing this from happening in the future.

Stay tuned for a message about changes to the station assignments for select tows, likely sometime next week.

**Comment by Curt-Whitmire-NOAA** [comment]
@iantaylor-NOAA @okenk @kellijohnson-NOAA @chantelwetzel-noaa I fixed the underlying data in the _catch_fact_ and _individual_fact_ tables that was causing the unexpected results from the PullCatch and PullBio functions. I've tested the data pulls for petrale sole, rex sole, canary RF, black RF, copper RF, shortspine and sablefish, but please let me know if you see any related inconsistencies when pulling data from other species.

I'm attaching a summary table of the trawl_id's that had incorrect **actual_station_design_whid** values. Values for this field have been changed in both the _catch_fact_ and _individual_fact_ tables, and the attached summary table shows the number of affected records for each unique trawl_id value.
[FRAM_DW_Unmatched_StationAssignment_Summary_v20230530.csv](https://github.com/pfmc-assessments/nwfscSurvey/files/11607125/FRAM_DW_Unmatched_StationAssignment_Summary_v20230530.csv)
