### ISSUE TITLE
outName is blank in `Pull*.fn()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#120]
`outName` is being set inside if statements for when `Name` or `SciName` are `NULL` to the null objects instead of `SciName` when `Name` is `NULL` and the opposite. This is leading to passing `NULL` to `paste()` in the ending filename. Thus, the resulting file name for the catch data is something like `Catch__NWFSC.Combo_2023-06-13.rda` where the species name should be in between the underscores. Line 111 and 117 should be switched.
https://github.com/pfmc-assessments/nwfscSurvey/blob/b9faa5db6cbfbc10d95129432fc620275bff08a7/R/PullCatch.fn.R#L107-L118

Line 67 and 73 should be switched.
https://github.com/pfmc-assessments/nwfscSurvey/blob/b9faa5db6cbfbc10d95129432fc620275bff08a7/R/PullBio.fn.R#L63-L75

Also, the following line should be moved  to the next if statement because right now it is changing the file name to use "All" when there is a common name but no scientific name, e.g., I pulled data with `Name = "sablefish" and got `Bio_All_AFSC.Slope_2023-06-12.rda`.
https://github.com/pfmc-assessments/nwfscSurvey/blob/b9faa5db6cbfbc10d95129432fc620275bff08a7/R/PullBio.fn.R#L74

@chantelwetzel-noaa I can open a pull request for this where I remove line 74 of `PullBio.fn()` and I set `outName <- Species` inside the first two if statements or `outName <- "All"` in the third if statement when there is no species name or common name passed to the functions.

**Comment by chantelwetzel-noaa** [comment]
The `Pull*.fn()` have been deprecated and replaced by `pull_*()` where this has been addressed.
