### ISSUE TITLE
Cannot specify `common_name` and `sci_name` in `pull_catch()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#125]
If you use both `common_name` and `sci_name` in `pull_catch()`, then nothing is set for `var_name` and `species` in the code because it assumes one of them will be `NULL`. See the following code that I am referring to:
https://github.com/pfmc-assessments/nwfscSurvey/blob/d371e6f4f6474ff436c53b02c8f6cafa3f76ba7d/R/pull_catch.R#L78-L89

Yet, there is no guidance in the documentation for this function that you cannot specify both. Where, I could see a user thinking oh the common name of this species is easier to spell so I will use it but it is unclear what the common name is for this other species so I will use its scientific name. I know this is an edge case but given we are currently working on this function, I thought that we should at least think about how to mitigate this.

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA Thank you for catching this!  This commit fixes this bug in a fairly straightforward manner.
