### ISSUE TITLE
Error in JSON query from `PullCatch.fn()`

### ISSUE THREAD

**Issue by seananderson** [pfmc-assessments/nwfscSurvey#133]
On running

```r
nwfscSurvey::PullCatch.fn(SurveyName = "NWFSC.Combo", SciName = "Squalus suckleyi")
```

(Any example species or all data is the same.)

The error is returned:

```
Pulling catch data. This can take up to ~ 30 seconds (or more).
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
```

The error comes from the first query at:

```r
 positive_tows <- try(get_json(url = url_text))
```

where `url_text` is

```
"https://www.webapps.nwfsc.noaa.gov/data/api/v1/source/trawl.catch_fact/selection.json?filters=project=Groundfish%20Slope%20and%20Shelf%20Combination%20Survey,station_invalid=0,performance=Satisfactory,depth_ftm>=30,depth_ftm<=700,field_identified_taxonomy_dim$scientific_name|=[%22Squalus%20suckleyi%22],date_dim$year>=1980,date_dim$year<=5000&variables=common_name,scientific_name,project,year,vessel,tow,total_catch_numbers,total_catch_wt_kg,subsample_count,subsample_wt_kg,cpue_kg_per_ha_der,statistical_partition_dim$statistical_partition_type,partition,operation_dim$legacy_performance_code"
```

The error, of course, is because that URL is currently returning an [error page](https://www.webapps.nwfsc.noaa.gov/data/api/v1/source/trawl.catch_fact/selection.json?filters=project=Groundfish%20Slope%20and%20Shelf%20Combination%20Survey,station_invalid=0,performance=Satisfactory,depth_ftm%3E=30,depth_ftm%3C=700,field_identified_taxonomy_dim$scientific_name|=[%22Squalus%20suckleyi%22],date_dim$year%3E=1980,date_dim$year%3C=5000&variables=common_name,scientific_name,project,year,vessel,tow,total_catch_numbers,total_catch_wt_kg,subsample_count,subsample_wt_kg,cpue_kg_per_ha_der,statistical_partition_dim$statistical_partition_type,partition,operation_dim$legacy_performance_code).

This was working a couple weeks ago, so I assume something might have changed on the server, or maybe there are just temporary issues with the server? Just posting this in case there is something somebody can fix somewhere.

**Comment by chantelwetzel-noaa** [comment]
@seananderson I just confirmed that I, too, am unable to access the data with the code.  I also checked the online tool which appears to not be working either.  I have emailed our database staff and will update when I know more.

**Comment by chantelwetzel-noaa** [comment]
The data warehouse is back online and should once again be working as expected.  Sorry for any inconvenience this may have caused.
