### ISSUE TITLE
Create consistent messages from `pull_*()` functions

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#160]
When using `pull_bio()` I get this warning mixed in with all of the {cli} output, `
Initiating curl with CURL_SSL_BACKEND: openssl`. Also, the warning for `dir` is not a {cli} message. It would be great to make the first line come from cli with the appropriate "x" or "i" depending on what you see best and remove the warning from {curl} because it is benign. See below for actual output and I am guessing all `pull_*()` functions have this problem but I did not check.
```
Output will not be saved in `dir` because dir = NULL.
ℹ Pulling biological data for sablefish.
Initiating curl with CURL_SSL_BACKEND: openssl
ℹ There were 95647 biological samples pulled.
ℹ There were 767 biological samples with non-satisfactory tow performance (e.g., no area swept estimate, net issues, etc.).
ℹ There were 567 biological samples from stations that have been removed from the standard station list.
ℹ There were 81 biological samples that are outside the standard depth range.
ℹ There were 94232 biological samples remaining after applying standard filtering.
```

**Comment by chantelwetzel-noaa** [comment]
Commit 52b604e59a0504874a459b8336ed129779e510e0 has fixed the messaging. I am not getting a similar warning from the `curl` package.  Can you tell me which `curl` package version you have installed?

**Comment by iantaylor-NOAA** [comment]
Update: the curl message seems to be from here: https://github.com/jeroen/curl/blob/master/src/ssl.c#L16.
It seems that you could capture that message as discussed in https://stackoverflow.com/questions/49694552/suppress-messages-from-underlying-c-function-in-r but also that it's not recommended because you might miss important messages.

**Comment by chantelwetzel-noaa** [comment]
Thank you @iantaylor-NOAA.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for digging into the {curl} message. I totally think that we can ignore this message and not worry about it being printed to the screen. For what it is worth, my version of {curl} is 5.1.0. (don't judge 🤣 because the latest on CRAN is 6.0.0).

**Comment by chantelwetzel-noaa** [comment]
Haha!  I blame the {curl} package since it can be a pain to update (at least for me) since the previous install cannot be removed, requiring detaching and hand deletion.
