### ISSUE TITLE
export stopifnotcolumn or use nwfscSurvey:::stopifnotcolumn?

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#161]
@chantelwetzel-noaa the following function is not exported and it is duplicated in PacFIN.Utilities
https://github.com/pfmc-assessments/nwfscSurvey/blob/0386065440c1190825a707a7644851ee8a2d073e/R/stopifnot.R#L12

I am wondering if we should use nwfscSurvey:::stopifnotcolumn() in PacFIN.Utilities, which is known to not be the best practice but we are not submitting to CRAN so 🤷 or should we export it from {nwfscSurvey}? Either option is fine with me, I just do not want to have the code in two places.

**Comment by chantelwetzel-noaa** [comment]
I think it would be easiest to export this function in {nwfscSurvey}.

**Comment by kellijohnson-NOAA** [comment]
Okay great, I will wait for that to happen before I deprecate it from PacFIN.Utilities.
