### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ericward-noaa** [pfmc-assessments/nwfscSurvey#33]
I updated the documentation, removing deprecated args, and including ones that weren't in functions. 

Two improvements:
1. It'd be useful to have others go through the various functions and make sure parameters are well documented. 
2. It'd be good to put some more minimal examples, so they'd be accessible in the help files. I did this previously for PullBio / PullCatch / PullHaul functions -- so folks can use that format as a template

**Comment by iantaylor-NOAA** [comment]
Hi @ericward-noaa, thanks for all your changes in commit 5f160c1736832141f9cb369aa5a9504e3cd0ad84 and the new "R-CMD-check" passing badge that results. It looks like you also ran `styler::style_pkg()` which makes it easier to read all the code in here (most of which predates the invention of tindyverse style).

As I go through the process of using these functions I will try to add examples as I go. On the one hand, most of us who work with this package are super busy with stock assessments right now. On the other hand, we're also using the package a lot as a result.

**Comment by ericward-noaa** [comment]
@iantaylor-NOAA Great - let me know how else I can help if you need it

**Comment by kellijohnson-NOAA** [comment]
Also, use @family tag as I suggested we would do in #42.
