### ISSUE TITLE
fyi GH org name change but old links there

### ISSUE THREAD

**Issue by eeholmes** [pfmc-assessments/nwfscSurvey#82]
to `nwfsc-assess` instead of new `pfmc-assessments`

**Comment by iantaylor-NOAA** [comment]
Thanks for the reminder @eeholmes. It looks like everything in the README still works with the old links, including the R-CMD-check badge and the `install_github()` command, but obviously it's a good idea to update the github org name in this package and all others as soon as we get the chance.

**Comment by kellijohnson-NOAA** [comment]
All links have now been changed except those in the three folders that will be removed (#96).
Done in
bdb6049541e4a29a5ee24086569fcce27d149ea5
1d723d5c4cb22453baef6963b56265ac6b52114f
e4d6b70c214cefbaf0b29dee689d419ad63bffb1
