### ISSUE TITLE
Increase documentation for survey names

### ISSUE THREAD

**Issue by okenk** [pfmc-assessments/nwfscSurvey#83]
Which SurveyName is the WCGBTS? I think it is NWFSC.Combo, but this should be specified.

**Comment by chantelwetzel-noaa** [comment]
Agreed. Historically, this survey was called many things but one of them was the NWFSC Combination Shelf-Slope survey. Hence, the linkage to the name NWFSC.Combo was clearer. Since we have moved away from this name clarity in the documentation is definitely needed.  Thank you!
