### ISSUE TITLE
Fail if dir does not exist

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#90]
@chantelwetzel-noaa do you mind if I change this to attempt to create the dir and only fail if it cannot be created? That way users would not have to ensure that the directory is created before downloading the data?

https://github.com/pfmc-assessments/nwfscSurvey/blob/e8fb295fa391d4509f22acf6f021e516d21ede83/R/check_dir.R#L23-L24

**Comment by chantelwetzel-noaa** [comment]
Sure. I think we should also expand the function to create an additional folder if needed (e.g., forSS, plots) so we could use this function inside multiple functions.  Here is an example of a call within a plotting function of what we may want to add:

````
    if (is.null(dir)) {
      stop("Directory needs to be set.")
    }
    if (!file.exists(dir)) {
      stop("The dir argument leads to a location", ",\ni.e., ", dir, ", that doesn't exist.")
    }

    plotdir <- file.path(dir, paste("plots", sep = ""))
    plotdir.isdir <- file.info(plotdir)$isdir
    if (is.na(plotdir.isdir) | !plotdir.isdir) {
      dir.create(plotdir)
    }
    if (is.null(dir)) {
      stop("Directory needs to be set.")
    }
    if (!file.exists(dir)) {
      stop("The dir argument leads to a location", ",\ni.e., ", dir, ", that doesn't exist.")
    }

    plotdir <- file.path(dir, paste("plots", sep = ""))
    plotdir.isdir <- file.info(plotdir)$isdir
    if (is.na(plotdir.isdir) | !plotdir.isdir) {
      dir.create(plotdir)
    }
````

**Comment by iantaylor-NOAA** [comment]
I like this change. Could you also change from
`dir.create(plotdir)` to `dir.create(plotdir, recursive = TRUE)`?

That would allow someone to provide an input like
`pull_biological_samples(dir = "project/species")` where both `project` and `species` within it haven't been created yet.

**Comment by kellijohnson-NOAA** [comment]
Will do @iantaylor-NOAA :grin:

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa do you have any desire to remove `dopng` and just rely on `is.null(dir)` where if `dir = NULL` then it would have the same behavior as `dopng = FALSE` but need one less argument? Feel free to say do not touch this 😆 . I am only asking because I cannot accommodate two different error messages
```
    if (is.null(dir)) {
      stop("Directory needs to be set.")
    }
```
versus what is currently in `check_dir()`
```
  if (is.null(dir)) {
    if (verbose) {
      message("Output will not be saved to since dir is not specified.")  
    }   
  }
```

**Comment by chantelwetzel-noaa** [comment]
I think we can remove the `dopng` input and just assume that if a user passes a `dir` then they want files to be save.  Thank you.
