### ISSUE TITLE
Remove Examples, docs, and doc

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscSurvey#96]
We will be removing the Examples, docs, and doc directories. In preparation for this we need to
- [x] move the info in [cleaning_AKSlope_Data_example](https://github.com/pfmc-assessments/nwfscSurvey/blob/13a27a9c08aace9c8033ea07e44e0fe26922922c/Examples/cleaning_AKSlope_Data_example.R) to the vignette (@chantelwetzel-noaa)
- [x] git rm Examples, doc, docs, and Meta directories (@kellijohnson-NOAA)
- [ ] when there are no branches ... increment version number and permanently remove directories and all history of the three directories (@kellijohnson-NOAA)

**Comment by chantelwetzel-noaa** [comment]
I opted to add the example of how to run the cleaning_AKSlope_Data_example into the functions documentation (7bb205f82332bd7dcd1ab257c9bc6136f0f151a3)

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa can I also delete Meta?

**Comment by chantelwetzel-noaa** [comment]
Given that I had no idea what this was, yes. This appears to be something that is no longer being used. Thank you.
